package: mediapool_rename
version: '3.0.0'
author: 'Alexander Walther, based on explorit* new media'
supportpage: https://github.com/alexplusde/mediapool_rename

requires:
    php:
        version: '>=8.3,<9'
    redaxo: '^5.18.3'
    packages:
        mediapool: '>=2.15.0'
        metainfo: '>=2.10.0'

page:
    title: translate:mediapool_rename_title
    hidden: true

default_config:
    excluded_table_patterns: "_history\ntmp_"

pages:
    mediapool/rename:
        title: translate:mediapool_rename_title
        perm: mediapool_rename[]
        subpages:
            settings:
                title: translate:mediapool_rename_settings
                icon: rex-icon fa-cog
                itemClass: pull-right
                perm: admin
            docs:
                title: translate:mediapool_rename_docs
                subPath: README.md
                icon: rex-icon fa-info-circle
                itemClass: pull-right
                perm: admin

installer_ignore:
    - .git
    - .gitignore
    - .github
    - node_modules
